version: 2


jobs:
  
  build:
    
    docker:
      - image: circleci/python:3.7.0
    
    steps: 
      
      - checkout
      
        #- run: sudo apt-get install cython3 python3-dev python3-mpi4py python3-h5py python3-numpy python3-scipy python3-matplotlib python3-pandas
        #- run: sudo ln -s /usr/lib/python3/dist-packages/numpy/core/include/numpy/ /usr/include/numpy
      - run: pip3 install -r pip-requirements.txt --user
      
      - run: coverage3 run setup.py test
      - run: coverage3 report --include=$PWD/* --omit=$PWD/.eggs/*

      - run: python3 setup.py install --user


