version: 2


jobs:
  
  build:
    
    docker:
      - image: circleci/python:3.7.0
    
    steps: 
      
      - checkout
      
      - run: sudo apt-get install cython3 python3-dev python3-mpi4py python3-h5py python3-numpy python3-matplotlib
      - run: sudo pip install flake8 coveralls 
      
      #- run: flake8 .
      - run: coverage run setup.py test
      - run: coverage report --include=$PWD/*

      - run: python3 setup.py install --user


